@startuml

title __MODEL's Class Diagram__\n

  namespace com.chrisjaunes.communication.client {
    namespace group {
      namespace model {
        class com.chrisjaunes.communication.client.group.model.GInfo {
            - group : int
            - group_avatar : String
            - group_name : String
            + getGroup()
            + getGroup_avatar()
            + getGroup_name()
            + setGroup()
            + setGroup_avatar()
            + setGroup_name()
        }
      }
    }
  }
  

  namespace com.chrisjaunes.communication.client {
    namespace group {
      namespace model {
        class com.chrisjaunes.communication.client.group.model.GInfoView {
            ~ avatar : Bitmap
            + GInfoView()
            + getAvatar()
            + getGroup()
            + getGroupName()
        }
      }
    }
  }
  

  namespace com.chrisjaunes.communication.client {
    namespace group {
      namespace model {
        class com.chrisjaunes.communication.client.group.model.GMember {
        }
      }
    }
  }
  

  namespace com.chrisjaunes.communication.client {
    namespace group {
      namespace model {
        class com.chrisjaunes.communication.client.group.model.GMessage {
            - account : String
            - content : String
            - contentType : int
            - group : int
            - sendTime : String
            + GMessage()
            + GMessage()
            + getAccount()
            + getContent()
            + getContentType()
            + getGroup()
            + getSendTime()
            {static} + jsonToTMessage()
            + setAccount()
            + setContent()
            + setContentType()
            + setGroup()
            + setSendTime()
        }
      }
    }
  }
  

  namespace com.chrisjaunes.communication.client {
    namespace group {
      namespace model {
        class com.chrisjaunes.communication.client.group.model.GroupConfig {
            {static} + STATUS_ADD_SUCCESSFUL : String
            {static} + STATUS_QUERY_GROUP_SUCCESSFUL : String
            {static} + STR_ACCOUNT : String
            {static} + STR_CONTENT : String
            {static} + STR_CONTENT_TYPE : String
            {static} + STR_CONTENT_TYPE_TEXT : int
            {static} + STR_GROUP : String
            {static} + STR_GROUP_MEMBER_LIST : String
            {static} + STR_GROUP_NAME : String
            {static} + STR_SEND_TIME : String
            {static} + STR_TIME : String
            {static} + URL_GROUP_ADD : String
            {static} + URL_GROUP_ADD_MESSAGE : String
            {static} + URL_GROUP_QUERY : String
            {static} + URL_GROUP_QUERY_MESSAGE : String
        }
      }
    }
  }
  

  namespace com.chrisjaunes.communication.client {
    namespace group {
      namespace model {
        interface com.chrisjaunes.communication.client.group.model.GroupDao {
            {abstract} + InsertMessage()
            {abstract} + InsertMessageList()
            {abstract} + isMessageExist()
            {abstract} + queryMessageAboutGroup()
        }
      }
    }
  }
  

  namespace com.chrisjaunes.communication.client {
    namespace group {
      namespace model {
        interface com.chrisjaunes.communication.client.group.model.GroupRetrofit {
            {abstract} + addGroup()
            {abstract} + addMessage()
            {abstract} + query()
            {abstract} + queryMessage()
        }
      }
    }
  }
  

  com.chrisjaunes.communication.client.group.model.GInfoView o-- com.chrisjaunes.communication.client.group.model.GInfo : gInfo


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
