GET http://localhost:8080/communicationServer/

> {%
client.global.set("host", "localhost:8080/communicationServer/");
 %}

###

GET http://{{host}}/account/register

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
  client.assert(response.body === "[ERROR] 不应该使用GET访问", "Response Body is Error");
});
%}
###

POST http://{{host}}/account/register?account=666&password=666

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
  client.assert(response.contentType.mimeType === "application/json", "Expected 'application/json' but received");
  client.assert(response.body.status === "register successful");
});
%}

###

POST http://{{host}}/account/register?account=666&password=666

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
  client.assert(response.contentType.mimeType === "application/json", "Expected 'application/json' but received");
  client.assert(response.body.status === "account is exist");
});
%}

###

POST http://{{host}}/account/register?account=777&password=777&nickname=777&text_style={color:"#ffffff"}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
  client.assert(response.contentType.mimeType === "application/json", "Expected 'application/json' but received ");
  client.assert(response.body.status === "register successful");
});
%}

###


