POST http://localhost:8080/communicationServer/account/login?account=aaa&password=aaa

> {%
client.global.set("host", "localhost:8080/communicationServer/");
client.log(response.headers.valuesOf("Set-Cookie"));
//client.global.set("cookie", response.headers.valueOf("JSESSIONID"));
 %}

###
POST http://{{host}}/contacts/update?account2=bbb&time=2020-11-27 00:00:00&operation=request

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
  client.assert(response.contentType.mimeType === "application/json", "Expected 'application/json' but received");
  client.assert(response.body.status === "update successful");
});
%}
###
POST http://{{host}}/contacts/update?account2=ccc&time=2020-11-27 00:00:00&operation=request

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
  client.assert(response.contentType.mimeType === "application/json", "Expected 'application/json' but received");
  client.assert(response.body.status === "update successful");
});
%}
###
POST http://{{host}}/contacts/update?account2=ddd&time=2020-11-27 00:00:00&operation=request

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
  client.assert(response.contentType.mimeType === "application/json", "Expected 'application/json' but received");
  client.assert(response.body.status === "update successful");
});
%}

###
POST http://{{host}}/contacts/update?account2=eee&time=2020-11-27 00:00:00&operation=request

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
  client.assert(response.contentType.mimeType === "application/json", "Expected 'application/json' but received");
  client.assert(response.body.status === "update successful");
});
%}

###
POST http://localhost:8080/communicationServer/account/login?account=bbb&password=bbb

> {%
client.log(response.headers.valuesOf("Set-Cookie"));
 %}
###
POST http://{{host}}/contacts/update?account2=aaa&time=2020-11-27 00:00:00&operation=agree

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
  client.assert(response.contentType.mimeType === "application/json", "Expected 'application/json' but received");
  client.assert(response.body.status === "update successful");
});
%}
###
POST http://localhost:8080/communicationServer/account/login?account=ccc&password=ccc

> {%
client.log(response.headers.valuesOf("Set-Cookie"));
 %}
###
POST http://{{host}}/contacts/update?account2=aaa&time=2020-11-27 00:00:00&operation=agree

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
  client.assert(response.contentType.mimeType === "application/json", "Expected 'application/json' but received");
  client.assert(response.body.status === "update successful");
});
%}
###
POST http://localhost:8080/communicationServer/account/login?account=ddd&password=ddd

> {%
client.log(response.headers.valuesOf("Set-Cookie"));
 %}
###
POST http://{{host}}/contacts/update?account2=aaa&time=2020-11-27 00:00:00&operation=reject

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
  client.assert(response.contentType.mimeType === "application/json", "Expected 'application/json' but received");
  client.assert(response.body.status === "update successful");
});
%}
###
