POST http://localhost:8080/communicationServer/account/login?account=111&password=111

> {%
client.global.set("host", "localhost:8080/communicationServer/");
client.log(response.headers.valuesOf("Set-Cookie"));
//client.global.set("cookie", response.headers.valueOf("JSESSIONID"));
 %}

###
GET http://{{host}}/contacts/query

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
  client.assert(response.body === "[ERROR] 不应该使用GET访问", "Response Body is Error");
});
%}

###
POST http://{{host}}/contacts/query

> {%

client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
  client.assert(response.contentType.mimeType === "application/json", "Expected 'application/json' but received");
  client.assert(response.body.status === "illegal parameter");
});
%}
###