POST http://localhost:8080/communicationServer/account/login?account=111&password=111

> {%
client.global.set("host", "localhost:8080/communicationServer");
client.log(response.headers.valuesOf("Set-Cookie"));
//client.global.set("cookie", response.headers.valueOf("JSESSIONID"));
 %}

###
POST http://{{host}}/talk/update?account2=222&send_time=2020-11-27 00:00:00&content_type=1&content=123456

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
  client.assert(response.contentType.mimeType === "application/json", "Expected 'application/json' but received");
    client.assert(response.body.status === "successful");
});
%}

###
POST http://{{host}}/talk/update?account2=222&send_time=2020-11-27 00:00:00&content_type=1&content=123456

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
  client.assert(response.contentType.mimeType === "application/json", "Expected 'application/json' but received");
    client.assert(response.body.status === "db illegal parameter");
});
%}

###
POST http://{{host}}/talk/update?account2=account_no_exist&send_time=2020-11-27 00:00:00&content_type=1&content=123456

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
  client.assert(response.contentType.mimeType === "application/json", "Expected 'application/json' but received");
    client.assert(response.body.status === "db illegal parameter");
});
%}

###